---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
spec:
  selector:
    matchLabels:
      app: analytics
  replicas: 2
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: zustsain/analytics
          ports:
            - containerPort: 3201
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
spec:
  selector:
    app: analytics
  ports:
    - protocol: TCP
      port: 3201
  type: LoadBalancer
