name: capstone
on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/git addlogin-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and Push Capston Analystic
        uses: docker/build-push-action@v2
        id: docker_build_data
        with:
          context: ./data
          file: ./data/Dockerfile
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/analytics

      - name: Build and Push Capstone Backend
        uses: docker/build-push-action@v2
        id: docker_build_backend
        with:
          context: ./backend
          file: ./backend/Dockerfile
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/backend

      - name: Build and Push Capstone Communication
        uses: docker/build-push-action@v2
        id: docker_build_logic
        with:
          context: ./logic
          file: ./logic/Dockerfile
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/communication

      - name: Verify
        run: echo ${{steps.docker_build_reverseproxy.outputs.digest}}
